name: Go

on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
      - main
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'

      - uses: actions/checkout@v3

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
